### ISSUE TITLE
may i get your wechat number?

### ISSUE THREAD

**Issue by laixiaodong** [Project-Robius-China/video_for_makepad_learn#1]
Hi, yifei
I learned about you from rustchinaconf2024 and was interested to see that you were working on Genui and Makepad.
I want to know more about the status and future of Makepad, so I want to connect with you.
look forwards to your reply~

**Comment by laixiaodong** [comment]
@syf20020816

**Comment by syf20020816** [comment]
syf20020816，actually this is  my wechat
